# Generated by Django 3.2.7 on 2021-09-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseRecipies', '0003_alter_recipies_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipies',
            name='description',
        ),
        migrations.AddField(
            model_name='recipies',
            name='description1',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='recipies',
            name='description2',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='recipies',
            name='description3',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='recipies',
            name='description4',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='image1',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='image2',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='image3',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='image4',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
