# Generated by Django 3.2.7 on 2021-09-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseRecipies', '0005_remove_recipies_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipies',
            name='name',
            field=models.CharField(default='', max_length=45),
        ),
    ]
