# Generated by Django 3.2.7 on 2021-09-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseRecipies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
