# Generated by Django 3.2.7 on 2021-09-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseRecipies', '0002_alter_recipies_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
