# Generated by Django 3.2.7 on 2021-10-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseRecipies', '0006_recipies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipies',
            name='audio',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
