# Generated by Django 3.2.7 on 2021-10-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseRecipies', '0007_recipies_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='audios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(default='', upload_to='audios/')),
            ],
        ),
        migrations.AlterField(
            model_name='recipies',
            name='audio',
            field=models.FileField(default='', upload_to='audios/'),
        ),
    ]
