# Generated by Django 3.2.7 on 2021-10-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseRecipies', '0008_auto_20211023_0210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='audios',
        ),
        migrations.RenameField(
            model_name='recipies',
            old_name='audio',
            new_name='audio1',
        ),
        migrations.AddField(
            model_name='recipies',
            name='audio2',
            field=models.FileField(default='', upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='recipies',
            name='audio3',
            field=models.FileField(default='', upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='recipies',
            name='audio4',
            field=models.FileField(default='', upload_to='audios/'),
        ),
    ]
