# Generated by Django 3.2.7 on 2021-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseaseRecipies', '0009_auto_20211023_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipies',
            name='audioDesc1',
            field=models.FileField(default='', upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='recipies',
            name='audioDesc2',
            field=models.FileField(default='', upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='recipies',
            name='audioDesc3',
            field=models.FileField(default='', upload_to='audios/'),
        ),
        migrations.AddField(
            model_name='recipies',
            name='audioDesc4',
            field=models.FileField(default='', upload_to='audios/'),
        ),
    ]
